[secrets]
Reemplaza 'TU_CLAVE_AQUI' con la clave real de tu API de Google Gemini.
Puedes obtenerla en https://aistudio.google.com/app/apikey.

GEMINI_API_KEY = AIzaSyAe0FspBANYgTFl8JmXeCtj0ttkz8vFpcc
